image: miktex/miktex

variables:
  MIKTEX_USERINSTALL: "$CI_PROJECT_DIR/miktex_cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - miktex_cache/ # Cache packages

stages:
  - build

build:
  stage: build
  script:
    - echo $MIKTEX_USERINSTALL
    - mpm --update-db
    - latexmk -pdf
    - ls -la ./
  artifacts:
    expire_in: 1 week
    paths:
      - "*.pdf"
