image: miktex/miktex

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - /miktex/.miktex/texmfs/install # Cache packages

stages:
  - build

build:
  stage: build
  script:
    - mpm --update-db
    - latexmk -pdf
  artifacts:
    expire_in: 1 week
    paths:
      - "*.pdf"
